Neos:
  Neos:
    fusion:
      autoInclude:
        Neos.NeosIo.Contributions: true
    translation:
      autoInclude:
        Neos.NeosIo.Contributions:
          - Main
    nodeTypes:
      groups:
        contributions:
          position: 'after general'
          label: 'Contributions'
