Neos:
  Neos:
    fusion:
      autoInclude:
        Neos.Presentation: true

Sitegeist:
  Monocle:
    defaultPackageKey: 'Neos.Presentation'
    hiddenPrototypeNamePatterns:
      - 'Sitegeist.Kaleidoscope:*'
    alwaysShowPrototypes: {  }
